[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Schappo", email = "gustavoschappo1612@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}
